# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-16 16:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=100)),
                ('house', models.CharField(max_length=10)),
                ('apartment', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.IntegerField(max_length=10)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Address')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MembershipOP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField()),
                ('is_closed', models.BooleanField(db_index=True, default=False)),
                ('is_processed', models.BooleanField(default=False)),
                ('phone', models.IntegerField(max_length=10, null=True)),
                ('name', models.TextField(null=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Buyer')),
            ],
        ),
        migrations.CreateModel(
            name='OrderPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Order')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('manufacturer', models.CharField(max_length=80)),
                ('all_weight', models.IntegerField()),
                ('weight_for_one', models.IntegerField()),
                ('category', models.CharField(choices=[('FR', 'Fruit'), ('VL', 'Vegetable'), ('GR', 'Grocery'), ('HN', 'Honey'), ('BT', 'Basket')], default='FR', max_length=2)),
                ('price', models.DecimalField(db_index=True, decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.AddField(
            model_name='orderposition',
            name='product',
            field=models.ManyToManyField(through='myapp.MembershipOP', to='myapp.Product'),
        ),
        migrations.AddField(
            model_name='membershipop',
            name='order_pos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.OrderPosition'),
        ),
        migrations.AddField(
            model_name='membershipop',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Product'),
        ),
    ]
