# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-16 17:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('F', 'Fruit'), ('V', 'Vegetable'), ('G', 'Grocery'), ('H', 'Honey'), ('B', 'Basket')], default='F', max_length=1),
        ),
    ]
