# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-20 16:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20161116_1707'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='membershipop',
            name='order_pos',
        ),
        migrations.RemoveField(
            model_name='membershipop',
            name='product',
        ),
        migrations.AddField(
            model_name='order',
            name='is_valid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderposition',
            name='count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RemoveField(
            model_name='orderposition',
            name='product',
        ),
        migrations.AddField(
            model_name='orderposition',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.Product'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='MembershipOP',
        ),
    ]
