# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-21 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20161120_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='closed_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
