# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-24 15:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20161124_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='object_id',
            field=models.PositiveIntegerField(db_index=True, null=True),
        ),
    ]
